name: health report

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '00 23 * * *'
  workflow_dispatch:

jobs:
  report:
    runs-on: windows-latest
    steps:
    - name: Health Report
      uses: djh29/SYSU-HealthReport@master
      with:
        netid: ${{secrets.NETID}}
        password: ${{secrets.PASSWORD}}
